name: sports_complete
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0+1
  carousel_slider: ^4.0.0
  dio: ^4.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.8
  intl: ^0.17.0
  scrollable_positioned_list: ^0.2.2
  sticky_headers: ^0.2.0
  webview_flutter: ^2.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
